//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpRefresher.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class raidboss {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal raidboss() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KpRefresher.Ressources.raidboss", typeof(raidboss).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adina.
        /// </summary>
        public static string adina {
            get {
                return ResourceManager.GetString("adina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bandit Trio.
        /// </summary>
        public static string bandit_trio {
            get {
                return ResourceManager.GetString("bandit_trio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cairn.
        /// </summary>
        public static string cairn {
            get {
                return ResourceManager.GetString("cairn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Camp.
        /// </summary>
        public static string camp {
            get {
                return ResourceManager.GetString("camp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Conjured Amalgamate.
        /// </summary>
        public static string conjured_amalgamate {
            get {
                return ResourceManager.GetString("conjured_amalgamate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decima.
        /// </summary>
        public static string decima {
            get {
                return ResourceManager.GetString("decima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deimos.
        /// </summary>
        public static string deimos {
            get {
                return ResourceManager.GetString("deimos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Escort.
        /// </summary>
        public static string escort {
            get {
                return ResourceManager.GetString("escort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gate.
        /// </summary>
        public static string gate {
            get {
                return ResourceManager.GetString("gate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gorseval.
        /// </summary>
        public static string gorseval {
            get {
                return ResourceManager.GetString("gorseval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Greer.
        /// </summary>
        public static string greer {
            get {
                return ResourceManager.GetString("greer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keep Construct.
        /// </summary>
        public static string keep_construct {
            get {
                return ResourceManager.GetString("keep_construct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Matthias.
        /// </summary>
        public static string matthias {
            get {
                return ResourceManager.GetString("matthias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mursaat Overseer.
        /// </summary>
        public static string mursaat_overseer {
            get {
                return ResourceManager.GetString("mursaat_overseer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Qadim.
        /// </summary>
        public static string qadim {
            get {
                return ResourceManager.GetString("qadim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Qadim the Peerless.
        /// </summary>
        public static string qadim_the_peerless {
            get {
                return ResourceManager.GetString("qadim_the_peerless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à River of Souls.
        /// </summary>
        public static string river_of_souls {
            get {
                return ResourceManager.GetString("river_of_souls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sabetha.
        /// </summary>
        public static string sabetha {
            get {
                return ResourceManager.GetString("sabetha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sabir.
        /// </summary>
        public static string sabir {
            get {
                return ResourceManager.GetString("sabir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Samarog.
        /// </summary>
        public static string samarog {
            get {
                return ResourceManager.GetString("samarog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Slothasor.
        /// </summary>
        public static string slothasor {
            get {
                return ResourceManager.GetString("slothasor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Soulless Horror.
        /// </summary>
        public static string soulless_horror {
            get {
                return ResourceManager.GetString("soulless_horror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spirit Woods.
        /// </summary>
        public static string spirit_woods {
            get {
                return ResourceManager.GetString("spirit_woods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statues.
        /// </summary>
        public static string statues_of_grenth {
            get {
                return ResourceManager.GetString("statues_of_grenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Twin Largos.
        /// </summary>
        public static string twin_largos {
            get {
                return ResourceManager.GetString("twin_largos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Twisted Castle.
        /// </summary>
        public static string twisted_castle {
            get {
                return ResourceManager.GetString("twisted_castle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ura.
        /// </summary>
        public static string ura {
            get {
                return ResourceManager.GetString("ura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vale Guardian.
        /// </summary>
        public static string vale_guardian {
            get {
                return ResourceManager.GetString("vale_guardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dhuum.
        /// </summary>
        public static string voice_in_the_void {
            get {
                return ResourceManager.GetString("voice_in_the_void", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Xera.
        /// </summary>
        public static string xera {
            get {
                return ResourceManager.GetString("xera", resourceCulture);
            }
        }
    }
}
