//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpRefresher.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class tokens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal tokens() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KpRefresher.Ressources.tokens", typeof(tokens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cardinal Adina&apos;s Token.
        /// </summary>
        public static string Adina {
            get {
                return ResourceManager.GetString("Adina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mai Trin&apos;s Coffer.
        /// </summary>
        public static string AetherbladeHideout {
            get {
                return ResourceManager.GetString("AetherbladeHideout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mai Trin&apos;s Magnificent Coffer.
        /// </summary>
        public static string AetherbladeHideoutCM {
            get {
                return ResourceManager.GetString("AetherbladeHideoutCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Boneskinner Ritual Vial.
        /// </summary>
        public static string Boneskinner {
            get {
                return ResourceManager.GetString("Boneskinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cairn Fragment.
        /// </summary>
        public static string Cairn {
            get {
                return ResourceManager.GetString("Cairn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Conjured Amalgamate Token.
        /// </summary>
        public static string ConjuredAmalgamate {
            get {
                return ResourceManager.GetString("ConjuredAmalgamate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dagda&apos;s Coffer.
        /// </summary>
        public static string CosmicObservatory {
            get {
                return ResourceManager.GetString("CosmicObservatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dagda&apos;s Magnificent Coffer.
        /// </summary>
        public static string CosmicObservatoryCM {
            get {
                return ResourceManager.GetString("CosmicObservatoryCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decima&apos;s Token.
        /// </summary>
        public static string Decima {
            get {
                return ResourceManager.GetString("Decima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fragment of Saul&apos;s Burden.
        /// </summary>
        public static string Deimos {
            get {
                return ResourceManager.GetString("Deimos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Desmina&apos;s Token.
        /// </summary>
        public static string Desmina {
            get {
                return ResourceManager.GetString("Desmina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dhuum&apos;s Token.
        /// </summary>
        public static string Dhuum {
            get {
                return ResourceManager.GetString("Dhuum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Turret Fragment.
        /// </summary>
        public static string Escort {
            get {
                return ResourceManager.GetString("Escort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gorseval Tentacle Piece.
        /// </summary>
        public static string Gorseval {
            get {
                return ResourceManager.GetString("Gorseval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Greer&apos;s Token.
        /// </summary>
        public static string Greer {
            get {
                return ResourceManager.GetString("Greer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Void&apos;s Coffer.
        /// </summary>
        public static string HarvestTemple {
            get {
                return ResourceManager.GetString("HarvestTemple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Void&apos;s Magnificent Coffer.
        /// </summary>
        public static string HarvestTempleCM {
            get {
                return ResourceManager.GetString("HarvestTempleCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Minister Li&apos;s Coffer.
        /// </summary>
        public static string KainengOverlook {
            get {
                return ResourceManager.GetString("KainengOverlook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Minister Li&apos;s Magnificent Coffer.
        /// </summary>
        public static string KainengOverlookCM {
            get {
                return ResourceManager.GetString("KainengOverlookCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keep Construct Rubble.
        /// </summary>
        public static string KeepConstruct {
            get {
                return ResourceManager.GetString("KeepConstruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à White Mantle Abomination Crystal.
        /// </summary>
        public static string Matthias {
            get {
                return ResourceManager.GetString("Matthias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recreation Room Floor Fragment.
        /// </summary>
        public static string MursaatOverseer {
            get {
                return ResourceManager.GetString("MursaatOverseer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assault Knights&apos; Coffer.
        /// </summary>
        public static string OldLionsCourt {
            get {
                return ResourceManager.GetString("OldLionsCourt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assault Knights&apos; Magnificent Coffer.
        /// </summary>
        public static string OldLionsCourtCM {
            get {
                return ResourceManager.GetString("OldLionsCourtCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Qadim&apos;s Token.
        /// </summary>
        public static string Qadim {
            get {
                return ResourceManager.GetString("Qadim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ether Djinn&apos;s Token.
        /// </summary>
        public static string QTP {
            get {
                return ResourceManager.GetString("QTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à River of Souls Token.
        /// </summary>
        public static string River {
            get {
                return ResourceManager.GetString("River", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sabetha Flamethrower Fragment Piece.
        /// </summary>
        public static string Sabetha {
            get {
                return ResourceManager.GetString("Sabetha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cardinal Sabir&apos;s Token.
        /// </summary>
        public static string Sabir {
            get {
                return ResourceManager.GetString("Sabir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impaled Prisoner Token.
        /// </summary>
        public static string Samarog {
            get {
                return ResourceManager.GetString("Samarog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Slothasor Mushroom.
        /// </summary>
        public static string Slothasor {
            get {
                return ResourceManager.GetString("Slothasor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statue Token.
        /// </summary>
        public static string Statue {
            get {
                return ResourceManager.GetString("Statue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cerus&apos;s Magnificent Coffer.
        /// </summary>
        public static string TempleOfFebe {
            get {
                return ResourceManager.GetString("TempleOfFebe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cerus&apos;s Coffer.
        /// </summary>
        public static string TempleOfFebeCM {
            get {
                return ResourceManager.GetString("TempleOfFebeCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Twin Largos Token.
        /// </summary>
        public static string TwinLargos {
            get {
                return ResourceManager.GetString("TwinLargos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ura&apos;s Token.
        /// </summary>
        public static string Ura {
            get {
                return ResourceManager.GetString("Ura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vale Guardian Fragment.
        /// </summary>
        public static string Vale {
            get {
                return ResourceManager.GetString("Vale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ribbon Scrap.
        /// </summary>
        public static string Xera {
            get {
                return ResourceManager.GetString("Xera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ankka&apos;s Coffer.
        /// </summary>
        public static string XunlaiJadeJunkyard {
            get {
                return ResourceManager.GetString("XunlaiJadeJunkyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ankka&apos;s Magnificent Coffer.
        /// </summary>
        public static string XunlaiJadeJunkyardCM {
            get {
                return ResourceManager.GetString("XunlaiJadeJunkyardCM", resourceCulture);
            }
        }
    }
}
